name: flutter_games
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.29.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  provider: ^6.1.5
  flame_audio: ^2.11.6
  flame_bloc: ^1.12.0
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/parallax/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/audio/
    - assets/images/corazon.png
    - assets/images/background/

  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
